name: slide_15
description: The ultimate puzzle.

version: 1.0.1+2

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^2.3.1
  share_plus: ^3.1.0
  store_redirect: ^2.0.1
  audioplayers: ^0.20.1
  fluttertoast: ^8.0.9
  flutter_launcher_icons: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.0.5

flutter_native_splash:
  android: true
  color: "#BB77ED"
  image: "assets/logo.png"

flutter_icons:
  image_path: "assets/logo.png"
  android: true


  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/